version: '26.1.1'

services:
  db:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bitacora_tcu
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: backend_container
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
