version: '26.1.1'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"  # Nginx escuchará en el puerto 80 y redirigirá al frontend y backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Asegúrate de que nginx.conf está en la raíz de tu proyecto
    depends_on:
      - frontend
      - backend

  db:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bitacora_tcu
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: backend_container
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
